server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:goldmedal-db
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
